import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { JavaCliService } from '../services/javaCliService';
import { FileService } from '../services/fileService';
import { ExtractRequestDto } from '../dto/requests';
import { ApiResponseDto, KeyExtractionResultDto } from '../dto/responses';

interface ExtractRouteBody {
  binFile: {
    name: string;
    data: string;
    size: number;
  };
  stableFile: {
    name: string;
    data: string;
    size: number;
  };
  findComma?: boolean;
}

export async function extractRoutes(fastify: FastifyInstance) {
  const javaCliService = new JavaCliService();
  const fileService = new FileService();

  fastify.post<{ Body: ExtractRouteBody }>('/key', {
    schema: {
      summary: 'Extract cryptographic key from binary dump using stable positions',
      description: 'Extracts a cryptographic key from a binary memory dump using previously generated stable bit positions',
      body: {
        type: 'object',
        properties: {
          binFile: {
            type: 'object',
            description: 'Binary memory dump file',
            properties: {
              name: { 
                type: 'string', 
                description: 'Filename (e.g. tiva_reading_26181245.txt)'
              },
              data: { 
                type: 'string', 
                description: 'Base64 encoded file content'
              },
              size: { 
                type: 'number', 
                description: 'File size in bytes'
              }
            },
            required: ['name', 'data', 'size']
          },
          stableFile: {
            type: 'object',
            description: 'Stable positions file (generated by /api/stable/generate)',
            properties: {
              name: { 
                type: 'string', 
                description: 'Filename must end with .pos',
                pattern: '\\.pos$'
              },
              data: { 
                type: 'string', 
                description: 'Base64 encoded stable positions file'
              },
              size: { 
                type: 'number', 
                description: 'File size in bytes'
              }
            },
            required: ['name', 'data', 'size']
          },
          findComma: { 
            type: 'boolean', 
            description: 'Find comma delimiter in data',
            default: false
          }
        },
        required: ['binFile', 'stableFile']
      },
      response: {
        200: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            data: { type: 'object', additionalProperties: true },
            timestamp: { type: 'string' }
          }
        }
      }
    }
  }, async (request: FastifyRequest<{ Body: ExtractRouteBody }>, reply: FastifyReply) => {
    try {
      const { binFile: rawBinFile, stableFile: rawStableFile, findComma = false } = request.body;

      if (!rawBinFile || !rawStableFile) {
        return reply.status(400).send({
          success: false,
          error: 'Both binary file and stable position file are required',
          timestamp: new Date().toISOString()
        } as ApiResponseDto);
      }

      const binFile = {
        name: rawBinFile.name,
        data: Buffer.from(rawBinFile.data, 'base64'),
        size: rawBinFile.size
      };

      const stableFile = {
        name: rawStableFile.name,
        data: Buffer.from(rawStableFile.data, 'base64'),
        size: rawStableFile.size
      };

      const binValidation = fileService.validateFile(binFile);
      const stableValidation = fileService.validateFile(stableFile);

      if (!binValidation.isValid || !stableValidation.isValid) {
        const errors = [
          ...binValidation.errors.map(e => ({ ...e, file: 'binFile' })),
          ...stableValidation.errors.map(e => ({ ...e, file: 'stableFile' }))
        ];

        return reply.status(400).send({
          success: false,
          error: 'File validation failed',
          data: { validationErrors: errors },
          timestamp: new Date().toISOString()
        } as ApiResponseDto);
      }

      if (!stableFile.name.endsWith('.pos')) {
        return reply.status(400).send({
          success: false,
          error: 'Stable file must have .pos extension',
          timestamp: new Date().toISOString()
        } as ApiResponseDto);
      }

      const extractRequest: ExtractRequestDto = {
        binFile,
        stableFile,
        findComma
      };

      const result = await javaCliService.extractKey(extractRequest);

      return reply.status(200).send({
        success: true,
        data: result,
        timestamp: new Date().toISOString()
      } as ApiResponseDto<KeyExtractionResultDto>);

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      
      return reply.status(500).send({
        success: false,
        error: errorMessage,
        timestamp: new Date().toISOString()
      } as ApiResponseDto);
    }
  });

  fastify.get('/health', {
    schema: {
      summary: 'Health check for extract service',
      description: 'Returns the health status of the extract service',
      response: {
        200: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            data: {
              type: 'object',
              properties: {
                service: { type: 'string' },
                status: { type: 'string' },
                timestamp: { type: 'string' }
              }
            },
            timestamp: { type: 'string' }
          }
        }
      }
    }
  }, async (_, reply: FastifyReply) => {
    return reply.status(200).send({
      success: true,
      data: {
        service: 'extract',
        status: 'healthy',
        timestamp: new Date().toISOString()
      },
      timestamp: new Date().toISOString()
    } as ApiResponseDto);
  });
}